import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: 1,
    nom: "La tête dans les nuages",
    desc: "Site de coiffure à domicile — prise de RDV, prestations, espace client",
    tech: ["TypeScript", "React", "Next.js", "Vercel"],
    url: "https://latetedanslesnuages-web.vercel.app",
    type: "browser",
    color: "#F5F0EB",
    emoji: "☁️",
  },
  {
    id: 2,
    nom: "Dyarna",
    desc: "Guide touristique marocain — villes, gastronomie & traditions",
    tech: ["Angular", "TypeScript", "SCSS", "Vercel"],
    url: "https://snapnest-weld.vercel.app",
    type: "browser",
    color: "#F5EBE0",
    emoji: "🇲🇦",
  },
  {
    id: 3,
    nom: "App Zenbulle",
    desc: "Application mobile de bien-être et méditation",
    tech: ["React Native", "Expo", "JavaScript"],
    url: "https://app-zenbulle.vercel.app",
    type: "mobile",
    color: "#F0EBF5",
    emoji: "🧘",
  },
  {
    id: 4,
    nom: "TotoApp",
    desc: "Application de gestion de tâches personnelles",
    tech: ["React", "Tailwind CSS"],
    url: "https://todo-app-hazel-iota-13.vercel.app/",
    type: "browser",
    color: "#EBF5F0",
    emoji: "✅",
  },
];

export const CV_PROJECTS: Project[] = [
  {
    id: 1,
    nom: "La tête dans les nuages — API",
    desc: "API REST complète",
    tech: ["TypeScript", "Node.js", "Express"],
    url: null,
    type: "browser",
    color: "",
    emoji: "☁️",
  },
  {
    id: 2,
    nom: "La tête dans les nuages — Web",
    desc: "Interface web élégante",
    tech: ["TypeScript", "React"],
    url: null,
    type: "browser",
    color: "",
    emoji: "🌐",
  },
  {
    id: 3,
    nom: "La tête dans les nuages — Blog",
    desc: "Blog avec gestion de contenu",
    tech: ["TypeScript", "React"],
    url: null,
    type: "browser",
    color: "",
    emoji: "✍️",
  },
  {
    id: 4,
    nom: "Dyarna",
    desc: "Guide touristique marocain",
    tech: ["Angular", "TypeScript", "SCSS"],
    url: "https://snapnest-weld.vercel.app",
    type: "browser",
    color: "",
    emoji: "🇲🇦",
  },
  {
    id: 5,
    nom: "App Zenbulle",
    desc: "App mobile bien-être",
    tech: ["React Native", "JS"],
    url: null,
    type: "mobile",
    color: "",
    emoji: "🧘",
  },
  {
    id: 6,
    nom: "TotoApp",
    desc: "Gestion de tâches",
    tech: ["React", "Tailwind"],
    url: "https://todo-app-hazel-iota-13.vercel.app/",
    type: "browser",
    color: "",
    emoji: "✅",
  },
];
